version: '3'

services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "localhost:${BACKEND_PORT}/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - text-cleaner

  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - text-cleaner


networks:
  text-cleaner:
    name: text-cleaner